artifacts_config:
  artifacts_dir: artifacts

data_ingestion_config:
  dataset_download_url: ra4u12/bookrecommendation
  genre_dataset_url: https://raw.githubusercontent.com/razyousuf/Book-Recommendation-Clustering-Pipeline/refs/heads/main/Experiment/genres.csv
  dataset_dir: dataset
  ingested_dir: ingested_data
  raw_data_dir: raw_data

data_validation_config:
  cleaned_data_dir: cleaned_data
  serialized_objects_dir: serialized_objects
  book_csv_file: BX-Books.csv
  rating_csv_file: BX-Book-Ratings.csv
  genre_csv_file: genre.csv

data_transformation_config:
  transformed_data_dir: transformed_data

model_trainer_config:
  trained_model_dir: trained_model
  trained_model_name: model.pkl

recommendation_config:
  poster_api_url: https://api.themoviedb.org/3/movie/{}?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US
